---
name: continuous-integration
on: [push, pull_request]

jobs:
  test-package:
    runs-on: ubuntu-latest
    #container: ghcr.io/${{ github.repository }}/ci-image:latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and its dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Run pytest
        run: pytest -v --cov --cov-report json

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: python-${{ matrix.python-version }}
